services:
  ding-tech-db:
    image: postgres:17-alpine
    container_name: ding-tech-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_OUTER:-5432}:${DB_PORT:-5432}"
    volumes:
      - ding-tech-db-data:/var/lib/postgresql/data

  ding-tech-api:
    build:
      context: ../
      dockerfile: src/Application.API/Dockerfile
    container_name: ding-tech-api
    depends_on:
      - ding-tech-db
    env_file:
      - .env
    environment:
      - ConnectionStrings__ApplicationConnection=Host=ding-tech-db;Port=${DB_PORT:-5432};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${API_PORT_OUTER:-8080}:8080"
      - "${API_HTTPS_PORT_OUTER:-8081}:8081"

volumes:
  ding-tech-db-data:
