services:
  ding-tech-db:
    image: postgres:17-alpine
    container_name: ding-tech-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_OUTER:-5432}:${DB_PORT:-5432}"
    volumes:
      - ./ding-tech-db-data:/var/lib/postgresql/data

volumes:
  ding-tech-db-data:
